config/routes.rb
Calendar::Application.routes.draw do

  resources :activities, :except => [:index] do
    collection do
      get 'search', to: 'activities#search', :as => :search
    end
  end

  resources :tags
  resources :departments, :except => [:destroy] do
    # member do
    #   post 'activities', :to => 'activities#create_department_activity', :as => :create_department_activity_for
    # end
    resources :department_activities
  end
  # namespace :admin do
  #   resources :departments, :only => [:new, :create, :destroy]
  # end
  resources :users, :only => [:new, :create, :show] do
    member do
      put 'departments', :to => 'users#add_department', :as => :add_department_to
    end
    resources :departments, :only => [:index]
    resources :notices
    resources :activities, :only => [:index]
    resource :calendar, :only => [:show]  
  end

  resource :session, :only => [:create, :destroy, :new]
  root to: "sessions#new"
  
end

app/views/shared/_menu.html.erb
<ul id="menu-bar">
  <li><%= link_to "Home", user_url(current_user) %></li>
  
  <li><a href="#">Activities</a>
    <ul>
      <li id="m-act"><%= link_to "My Activities",  user_activities_url(current_user) %></li>
      <li id="n-act"><%= link_to "New Activity", new_activity_url %></li>
      <li id="s-act"><%= link_to "Search Activities", search_activities_url %></li>
    </ul>
  </li>
  
  <li><a href="#">Departments</a>
  
    <ul>
      <li><%= link_to "New Department", new_department_url %></li>
      <li> <a href="#">My Departments</a> 
        <ul>
          <% current_user.departments.each do |dpt| %>
            <li>
              <%= link_to "#{dpt.dept_name} activities", department_department_activities_path(dpt.id) %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>
 </li>

 <li><%= link_to "Calendar", user_calendar_url(current_user) %></li>
 <li class="active" style="float:right;"><%= link_to "Logout", session_url, :method => :delete %></li>
</ul>

<script type="text/javascript">
	
</script>

<!-- departments_url -->