config/routes.rb
Calendar::Application.routes.draw do

  resources :activities, :except => [:index] do
    collection do
      get 'search', to: 'activities#search', :as => :search
    end
  end

  resources :tags
  resources :departments, :except => [:destroy] do
    # member do
    #   post 'activities', :to => 'activities#create_department_activity', :as => :create_department_activity_for
    # end
    resources :department_activities
  end
  # namespace :admin do
  #   resources :departments, :only => [:new, :create, :destroy]
  # end
  resources :users, :only => [:new, :create, :show] do
    member do
      put 'departments', :to => 'users#add_department', :as => :add_department_to
    end
    resources :departments, :only => [:index]
    resources :notices
    resources :activities, :only => [:index]
    resource :calendar, :only => [:show]  
  end

  resource :session, :only => [:create, :destroy, :new]
  root to: "sessions#new"
  
end

app/models/department.rb
class Department < ActiveRecord::Base
  # the department class is more or less just a 'group'
  # that can be used to organize users.
  # this should help with user who wish to work on projects together etc.
  has_and_belongs_to_many :users
  belongs_to :admin, :class_name => "User"
  has_many :activities, :as => :actionable
  attr_accessible :dept_name, :user_id

  def add_user(usr)
    self.users << usr
  end

  # This is here so that we can fetch a users departments via ajax
  # from the fullcalendar.
  # once we have the users departments, we can fetch those 
  # departments department activities, and populate those on 
  # the users calendar
  def as_json
    {
      :id => self.id,
      :admin_id => self.user_id,
      :dept_name => self.dept_name
    }
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  include DepartmentsHelper

  def show
    # we want to show: all users in the department as well as the current user
    @department = Department.find(params[:id])
    # for form helper
    @activity = Activity.new
    @users = @department.users
    @user = current_user
    respond_to do |format|
      format.html
      format.json { render json: @activity.as_json }
    end

  end

  def new
    @department = Department.new
  end

  def create
    # the only attribute that is accessible and required is dept_name
    @department = Department.new({:dept_name => params[:department][:dept_name], :user_id => current_user.id})
    @user = current_user
    if @department.save
      flash[:notice] = "Department #{@department.dept_name} was created successfully."
      redirect_to @department
    else
      flash[:warning] = "Something went wrong when trying to create #{params[:dept_name]} and it could not be created."
      redirect_to new_department_url
    end
  end

  def destroy

  end

  def index
    # we use the DepartmentsHelper to get the full list of all departments
    # we use this list to allow users to join departments
    @departments = current_user.departments
    respond_to do |format|
      format.html
      format.json do 
        activities_ls = add_depts_to_list(@departments)
        render json: activities_ls 
      end
    end
  end

  private

  def add_depts_to_list(departments)
    activities_ls = []
    @departments.each do |dept|
      activities_ls << dept.as_json
    end
    return activities_ls
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
  # this just lets us list all departments that can be selected nicely
  def departments_for_select
    Department.all.collect{ |d| [d.dept_name] }
  end
end

app/views/departments/_form.html.erb
<%= form_for @department do |f| %>
	<%= f.label :dept_name %>
	<%= f.text_field :dept_name %>

	<%= f.submit %>
<% end %>

app/views/departments/_new_dept_form.html.erb
<%= form_for @user, :url => add_department_to_user_url(@user) do |f| %>
	<%= f.label :department_name %>
	<%= f.select :departments, departments_for_select %>

	<%= f.submit "Join department" %>
<% end %>

app/views/departments/index.html.erb
<table class="ActivityTable">
	<tr>
		<td> Department Name </td>
		<td> Department Members </td>
	</tr>
	<% @departments.each do |d| %>
		<tr>
			<td> <%= link_to d.dept_name, department_path(d.id) %> </td>
			<td> 
				<% all_u = d.users.collect{|u| u.username}.join(", ") %>
				<%= all_u %>
			</td>
		</tr>	
	<% end %>
</table>

app/views/departments/new.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<%= render "form" %>

app/views/departments/show.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<h2> Add activity to Department </h2>
<%= @department.dept_name %>