config/routes.rb
Calendar::Application.routes.draw do

  resources :activities, :except => [:index] do
    collection do
      get 'search', to: 'activities#search', :as => :search
    end
  end

  resources :tags
  resources :departments, :except => [:destroy] do
    # member do
    #   post 'activities', :to => 'activities#create_department_activity', :as => :create_department_activity_for
    # end
    resources :department_activities
  end
  # namespace :admin do
  #   resources :departments, :only => [:new, :create, :destroy]
  # end
  resources :users, :only => [:new, :create, :show] do
    member do
      put 'departments', :to => 'users#add_department', :as => :add_department_to
    end
    resources :departments, :only => [:index]
    resources :notices
    resources :activities, :only => [:index]
    resource :calendar, :only => [:show]  
  end

  resource :session, :only => [:create, :destroy, :new]
  root to: "sessions#new"
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base

  attr_accessible :tag, :content, :status, :overview, :started, :finished, :start, :finish, :notify, :kind, :repeats, :repeats_freq

  # we want an activity to be able to belong to a user or department
  belongs_to :actionable, :polymorphic => true
  # each activity should belong to a user since two people shouldn't
  # be doing the exact same thing. If multiple people are doing similar
  # things, it can belong to a department
  belongs_to :user
  # note that an activity has a tag, which is just a string, and also has tags,
  # which are searchable parameters created from the tag string
  has_and_belongs_to_many :tags
  belongs_to :department
  has_many :notices, :dependent => :destroy
  scope :are_tagged, where(:tagged => true)

  # some html displayed attributes will exist, so we don't want any script nastiness
  validates :content, :format => {
    :without =>  /\A.*<script>.*\z/,
    :message => "contained something suspicious."
  }

  default_scope {order('started DESC')}

  paginates_per 25

  def self.search(options)
   
    case options[:search_by]
    when "Tag"
      case options[:owned_by]
      when "Me"
        search_by_tags_me(options[:search], options[:current_user])
      else
        search_by_tags_all(options[:search])
      end
    when "Status"
      case options[:owned_by]
      when "Me"
        search_by_status_me(options[:search], options[:current_user])
      else
        search_by_status_all(options[:search])
      end
    end
  end

  # allows these to be downloaded as csvs i guess.
  def self.to_csv(str,options={})
    # list the columns which we will be retrieving data for
    column_names = ["tag", "content", "status", "overview", "started", "finished"]
    CSV.generate(options) do |csv|
      #binding.pry
      csv << column_names
      str.each do |activity|
        csv << activity.attributes.values_at(*column_names)
      end
    end
  end
  # hash to put it important details in json form, which will be used in the ajax methods in full_calendar
  def as_json
    # if it belongs to a department, user_id = 0
    user_id = self.user ? self.user.id : 0  
    {
      :id => self.id,
      :notify => self.notify,
      :kind => self.kind,
      :current_state => self.status,
      :title => self.overview,
      :tag => self.tag,
      :long_description => self.content,
      :editable => true,
      :start => self.started,
      :finish => self.finished,
      :end => self.finished,
      :department_id => self.department_id,
      :user_id => user_id,
      :allDay => false,
      :url => Rails.application.routes.url_helpers.activity_path(id) 
    }
  end

  def as_dept_json
    json_object = self.as_json
    json_object[:url] = Rails.application.routes.url_helpers.department_department_activity_path(self[:department_id], self[:id])
    json_object
  end

  # split the tags and then set the 'tagged' boolean (to speed up search)
  def add_tags
    tags = split_tags
    if tags.empty?
      return nil
    else
      # try and add relations to tags
      add_tag_associations(tags)
    end
  end

  def destroy_notices_if_completed(current_status)
    if self.notices.any? && current_status == "Completed"
      self.notices.delete_all
    end
  end

  private

  # if the tag already exists, add it to the association
  # otherwise, try and create the tag, and add it to the association if successful
  # HAVE NOT YET HANDLED TAGS THAT ARE NOT SAVED
  def add_tag_associations(tags)
    tags.each do |tag|
      t = Tag.find_by_tag(tag)
      if t
        self.tags << t
      else
        t = Tag.new(:tag => tag)
        self.tags << t if t.save
      end
    end        
  end

  # if we split the tag string and wind up with an empty array, there are no tags
  def set_tagged_bool
    self.tag.split(" ").empty? ? self.tagged = false : self.tagged = true
  end

  # determine if tags exist: if so, we will split them up and add relations
  def split_tags
    set_tagged_bool
    self.tagged ? self.tag.split(" ") : []
  end

  def self.search_by_tags_me(search, user)
    search = search.split(" ")
    return [] if search == []
    # find all Tag objects that have their tag attribute equal to part of the search
    # and then find all activities which have those tags and belong to the current_user
    Tag.where(:tag => search).collect{|candidate| candidate.activities.where(:user_id => user.id)}.flatten
  end

  # pretty much the same as above
  def self.search_by_tags_all(search)
    search = search.split(" ")
    return [] if search == []
    Tag.where(:tag => search).collect{|candidate| candidate.activities}.flatten
  end

  def self.search_by_status_me(search, user)
    return [] if search == []
    Activity.where(:status => search.capitalize, :user_id => user.id)
  end

  def self.search_by_status_all(search)
    return [] if search == []
    Activity.where(:status => search.capitalize)
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  include ActivitiesHelper
  before_filter :require_current_user!

  def create
    @user = current_user
    safe_params = make_params
    @activity = Activity.new(safe_params)
    add_non_whitelisted_properties(@activity)
    if @activity.save
      if @activity.notify && @activity.status != "Completed"
        create_notice(@activity)
      end
      redirect_to activity_url(@activity)
    end
  end

  def update
    # when the ajax put is called in calendar.js, it wall pass thru a bunch of params
    # we find the activity that corresponds to the id param passed through

    @activity = Activity.find(params[:id])
    #  if it is a real activity

    if params[:activity]
      # and the Activity model is able to successfully update the attributes passed in for that activity by the ajax put
      # and saving the activity doesn't break things
      if @activity.update_attributes(params[:activity]) && @activity.save
        # then we render the updated attributes of our activity as json
        @activity.destroy_notices_if_completed(params[:activity][:status])
        render :json => @activity.as_json
        # if does not validate or save, show errors and go back
      else 
        # binding.pry
        flash[:error] = @activity.errors
        redirect_to :back
      end
    # If it isn't a real activity, render generic error
    else 
      respond_to do |format|
        format.js 
        format.json { render :json => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    # we need to redefine these variables because they are in the index html file
    # that is going to be rendered next
    @user = current_user
    @activities = current_user.activities
    render "index"
  end

  def new
    @user = current_user
    @activity = Activity.new
  end

  def index
    # unless searching for all
    # if params[:activities][:searching_for] =! '*'
    # we do not use Activity.where(:user_id => current_user.id) because we want to be able to look
    # at other users calendars.
    # else @activites = Activity.all
    @activities = Activity.where(:user_id => params["user_id"]).order(:started).page params[:page]
    # binding.pry
    @user = current_user
    respond_to do |format|
      format.html
      format.csv {send_data Activity.to_csv(@activities) }
      format.json { render :json => @activities.as_json }
    end
    
  end
  
  def show
    @activity = Activity.find(params[:id])
     respond_to do |format|
      format.html
      format.json { render json: @activity.as_json }
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end


end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def make_params
    wrap_params_into_nice_hash
  end

  def search
    # sample params hash:
    search_relevant_params = {:search => params[:search],:search_by => params[:search_by], :owned_by => params[:owned_by], :current_user => current_user}
    @activities = Activity.search(search_relevant_params)
  end

  def add_non_whitelisted_properties(activity)
    activity.add_tags
    activity.user = current_user
    activity.tagged = tagged?
  end

  private

  def tagged?
    params[:activity][:tag].any?
  end

  def create_notice(activity)
    notice = Notice.populate_default_activity_notice(activity)
    notice.save
  end

  # date selectors pass in 3 parameters
  # the single date param will be constructed from these 3
  def start_date
    params_list = params[:activity]
    year = params_list["started(1i)"].to_i
    month = params_list["started(2i)"].to_i
    day = params_list["started(3i)"].to_i
    hour = params_list["started(4i)"].to_i
    minute = params_list["started(5i)"].to_i
    DateTime.new(year,month,day,hour,minute)
  end

  def finish_date
    params_list = params[:activity]
    year = params_list["finished(1i)"].to_i
    month = params_list["finished(2i)"].to_i
    day = params_list["finished(3i)"].to_i
    hour = params_list["finished(4i)"].to_i
    minute = params_list["finished(5i)"].to_i
    if year == 0 || month == 0 || day == 0
      return nil
    else
      hour ||= 0
      minute ||= 0
      dt = DateTime.new(year,month,day,hour,minute)
      return dt
    end
  end

  # make sure that the overview is a string
  ["overview", "tag", "content", "kind"].each do |el|
    define_method "sanitize_#{el}" do
      params[:activity][el.intern].to_s
    end
  end

  # create a nice params to pass in
  def wrap_params_into_nice_hash
    hash =
      {
        "notify" => params[:activity][:notify],
        "kind" => sanitize_kind,
        "overview" => sanitize_overview,
        "content" => sanitize_content,
        "tag" => sanitize_tag,
        "started" => start_date,
        "finished" => finish_date,
        "status" => params[:activity][:status]
      }
  end
end

app/views/activities/_activity_table.html.erb
<div class = "ActivityTable">
<table>
	<tr>
		<td> Summary </td>
		<td> Tag </td>
		<td> Long Description </td>
		<td> Date Started </td>
		<td> Date Completed </td>
		<td> Status </td>
	</tr>
	<% @activities.each do |el| %>
		<tr>
			<td> <%= link_to el.overview, edit_activity_path(el.id) %> </td>
			<td> <%=h el.tag %> </td>
			<!-- div neccessary because of some css bull where overflow doesn't work well with tables. -->
			<td>
				<div> 
					<%= el.content.html_safe %> 
				</div>
			</td>
			<td> <%=h el.started %> </td>
			<% if el.finished.nil? %>
				<td> N/A </td>
			<% else %>
				<td> <%=h el.finished %> </td>
			<% end %>
			<td> <%=h el.status %> </td>
		</tr>
	<% end %>
</table>
</div>

app/views/activities/_form.html.erb
<div class="nice-form">
<%= form_for @activity do |f| %>
	<ul>
		<li>
			<%= f.label :tag %> 
			<%= f.text_field :tag, :class => 'tooltip', :title => "You can search for activities by tags. Accepts letters, numbers, spaces and underscores." %>
		</li>

		<li class='required'> 
			<%= f.label :overview, :class => 'required' %> 
			<%= f.text_field :overview, :class => 'tooltip', :title => "A quick synopsis of the activity. Required."  %>
		</li>

		<% if flash[:error] %>
			<% flash[:error].full_messages.each do |msg| %>
				<p class='error'><%= msg %></p>
			<% end %>
		<% end %>
		<li>
			<%= f.label :content %> 
			<%= f.text_area :content, :onkeyup => "changeSize(this);" %>
		</li>

		<li style="float:right; border:none;" class="tooltip" title="If selected, a notecard will appear on your homepage reminding you to complete this activity.">
				<%= f.label :notify, :title => ""%> 
				<%= f.check_box :notify, :title => "" %>
		</li>

		<li>
			<%= f.label :status %> 
			<%= f.select :status, options_for_select(['New', 'In Progress', 'Completed']) %>
		</li>

	<!-- 	<li style="float:right; border:none;">
				<%= f.label "Repeats Every nth day" %> 
				<%= f.text_field :repeats_freq, :placeholder => 7 %>
		</li>

		<li>
			<%= f.label :repeats %> 
			<%= f.check_box :repeats %>
		</li>
 -->

		<li>
			<%= f.label :started %>
			<%= f.datetime_select(:started, :default => {:hour => 12, :minute => 0}) %>
	 	</li>
		
		<li>
			<%= f.label :kind %> 
			<%= f.text_field :kind %>
		</li>

	 	<li>
			<%= f.label :finished %>
			<%= f.datetime_select :finished, :include_blank => true %>
		</li>

		<li>
			<%= f.submit %>
		</li>

		<% if params[:controller] == "departments" %>
			<% z = Department.find(params[:id]).users.collect{|n| n.username} %>
			<%= z %>
			<%= f.hidden_field :department_id, :value => params[:id] %>
		<% end %>
	
	<% end %>
	</ul>
<div>

<script>
	//change size. poached from http://www.sanwebe.com/2014/08/css-html-forms-designs
	function changeSize(el) {
	    el.style.height = "40px";
	    el.style.height = (el.scrollHeight) + "px";
	    return false;
	}
</script>

app/views/activities/_search_form.html.erb
<%= form_tag search_activities_url(@activities), :method => 'get' do |f| %>

	<%= label_tag "Search for" %>

	<%= text_field_tag :search, params[:search] %>

	<%= label_tag "By" %>

	<%= select_tag :search_by, options_for_select(["Tag", "Status"]) %>

	<%= label_tag "Belonging to" %>
	<!-- belonging_selections = ["Me", "All users"]  + current_user.departments.collect{|department| department.dept_name} -->
	<% belonging_selections = ["Me", "All users"] %>
	<%= select_tag :owned_by, options_for_select(belonging_selections) %>

	<%= submit_tag "OK" %>
<% end %>

app/views/activities/edit.html.erb
<%= render "form" %>

<%= link_to "Destroy", activity_path, :method => :delete %>

app/views/activities/index.html.erb
<h3><%= @user.username %>'s activities</h3>
<% activities_route =  user_activities_url(current_user) %>
<h3><%= link_to "Download activities as CSV", activities_route + ".csv" %></h3>
	<%= paginate @activities %>
<%= render "activity_table" %>

app/views/activities/new.html.erb
<%= render "form" %>

app/views/activities/search.html.erb
<%= render "search_form" %>
<% if @activities && !@activities.empty? %>
	<%= render "activity_table" %>
<% end %>

app/views/activities/show.html.erb
<%= @activity.tag %>
<%= @activity.overview %>
<br/ >
<%= @activity.started %>
<%= @activity.status %>
<br />
<%= @activity.content.html_safe %>
<%= link_to "Edit", edit_activity_path(@activity) %>

<%= link_to "Destroy", activity_path, :method => :delete %>